%% This file is autogenerated ...

%% This file contains virtual vehicle configuration information.

%% This file is saved at time 15-Apr-2026 12:11:12
                     ConfigInfos.Version = '25.1.0.2973910 (R2025a) Update 1';
                   ConfigInfos.SessionID = 'FSAE_IC.m';
                   ConfigInfos.LicStatus = [0,1,1,1,0,1,0,0,1];
                ConfigInfos.ProjPathText = 'C:\Users\brenn\Colorado School of Mines\GRP-Mines Formula - General\FSAE 2025-2026 (MF13)\Vehicle Subsystems\Suspension\Calculations\Matlab\VDBS\FSAE';
                    ConfigInfos.ProjPath = 'C:\Users\brenn\Colorado School of Mines\GRP-Mines Formula - General\FSAE 2025-2026 (MF13)\Vehicle Subsystems\Suspension\Calculations\Matlab\VDBS\FSAE\VirtualVehicle\VirtualVehicle';
                 ConfigInfos.SessionName = 'FSAE_IC';
                 ConfigInfos.XmlPathText = 'C:\Users\brenn\MATLAB\Projects\examples\VVCCustomCatalog.xml';
               ConfigInfos.TemplateModel = 'VirtualVehicleTemplateArchitecture';
          ConfigInfos.TemplatePlantModel = 'SimscapePlantModelsArchitecture';
                 ConfigInfos.ConfigModel = 'ConfiguredVirtualVehicleModel';
            ConfigInfos.ConfigPlantModel = 'ConfiguredSimscapePlantModel';
                    ConfigInfos.VehClass = 'Passenger Vehicle';
                     ConfigInfos.VehArct = 'Conventional Vehicle';
                      ConfigInfos.VehDyn = 1;
              ConfigInfos.PlantModelType = 'Simscape';
                  ConfigInfos.VehChassis = 'Vehicle Body 6DOF Longitudinal and Lateral';
%% Vehicle Configuration
ConfigInfos.FeatureVariantSelectedMap=containers.Map;
ConfigInfos.FeatureVariantSelectedMap('Active Differential Control') = 'No Control';
ConfigInfos.FeatureVariantSelectedMap('Axle Interconnect') = 'No Interconnect';
ConfigInfos.FeatureVariantSelectedMap('Battery Management System') = 'No BMS';
ConfigInfos.FeatureVariantSelectedMap('Body and Frame') = 'Vehicle Body 6DOF Longitudinal and Lateral';
ConfigInfos.FeatureVariantSelectedMap('Brake Control Unit') = 'Open Loop';
ConfigInfos.FeatureVariantSelectedMap('Brake System') = 'Brake System';
ConfigInfos.FeatureVariantSelectedMap('DC-DC Converter') = 'No DC-DC Converter';
ConfigInfos.FeatureVariantSelectedMap('Drive Shaft Torque Routing') = 'One Actuator RWD';
ConfigInfos.FeatureVariantSelectedMap('Driver') = 'Longitudinal Driver';
ConfigInfos.FeatureVariantSelectedMap('Drivetrain') = 'Rear Wheel Drive';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 1') = 'Electric Vehicle 1EM - Simple Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Motors') = 'NoEM';
ConfigInfos.FeatureVariantSelectedMap('Energy Storage') = 'No Battery';
ConfigInfos.FeatureVariantSelectedMap('Engine') = 'SI Simple Engine';
ConfigInfos.FeatureVariantSelectedMap('Engine Control Unit') = 'Simple ECU';
ConfigInfos.FeatureVariantSelectedMap('Environment') = 'Ambient Conditions';
ConfigInfos.FeatureVariantSelectedMap('Final Drive') = 'Final Drive';
ConfigInfos.FeatureVariantSelectedMap('Front Axle Compliances') = 'Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Front Brake Type') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Front Differential System') = 'No Differential';
ConfigInfos.FeatureVariantSelectedMap('Front Suspension') = 'Simscape Suspension Front';
ConfigInfos.FeatureVariantSelectedMap('Front Tire Data') = 'MF Tires Longitudinal Front';
ConfigInfos.FeatureVariantSelectedMap('Front Tire and Wheel') = 'Simscape MF Tires Front';
ConfigInfos.FeatureVariantSelectedMap('Power Generation') = 'Power Generation';
ConfigInfos.FeatureVariantSelectedMap('Powertrain') = 'Conventional Vehicle';
ConfigInfos.FeatureVariantSelectedMap('Rear Axle Compliances') = 'Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Rear Brake Type') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Rear Differential System') = 'Limited Slip Differential Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Suspension') = 'Simscape Suspension Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Tire Data') = 'MF Tires Longitudinal Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Tire and Wheel') = 'Simscape MF Tires Rear';
ConfigInfos.FeatureVariantSelectedMap('Sensor') = 'IMU Sensor';
ConfigInfos.FeatureVariantSelectedMap('Solver Configuration') = 'Solver Configuration';
ConfigInfos.FeatureVariantSelectedMap('Steering System') = 'Multibody Steering System';
ConfigInfos.FeatureVariantSelectedMap('Suspension System') = 'Suspension System';
ConfigInfos.FeatureVariantSelectedMap('Thermal Control Unit') = 'No Thermal Control';
ConfigInfos.FeatureVariantSelectedMap('Thermal System') = 'Constant Temperature';
ConfigInfos.FeatureVariantSelectedMap('Tire and Wheel System') = 'Tire and Wheel System';
ConfigInfos.FeatureVariantSelectedMap('Trailer') = 'No Trailer';
ConfigInfos.FeatureVariantSelectedMap('Transmission') = 'Ideal Fixed Gear Transmission';
ConfigInfos.FeatureVariantSelectedMap('Transmission Control Unit') = 'PRNDL Controller';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Architecture') = 'Conventional Vehicle';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Control Unit') = 'No VCU';

%% User Modified Data

           ConfigInfos.DataModified{1,1} = 'PlntVehMass';
           ConfigInfos.DataModified{1,2} = '228';
           ConfigInfos.DataModified{1,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{1,4} = 'PlntVehMass';
           ConfigInfos.DataModified{1,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{1,6} = 'Body and Frame';

           ConfigInfos.DataModified{2,1} = 'PlntVehDstCGFrntAxl';
           ConfigInfos.DataModified{2,2} = '0.78372';
           ConfigInfos.DataModified{2,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{2,4} = 'PlntVehDstCGFrntAxl';
           ConfigInfos.DataModified{2,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{2,6} = 'Body and Frame';

           ConfigInfos.DataModified{3,1} = 'PlntVehDstCGRearAxl';
           ConfigInfos.DataModified{3,2} = '0.75298';
           ConfigInfos.DataModified{3,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{3,4} = 'PlntVehDstCGRearAxl';
           ConfigInfos.DataModified{3,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{3,6} = 'Body and Frame';

           ConfigInfos.DataModified{4,1} = 'PlntVehCGHgtAxl';
           ConfigInfos.DataModified{4,2} = '0.1105';
           ConfigInfos.DataModified{4,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{4,4} = 'PlntVehCGHgtAxl';
           ConfigInfos.DataModified{4,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{4,6} = 'Body and Frame';

           ConfigInfos.DataModified{5,1} = 'PlntVehRollMomentInertia';
           ConfigInfos.DataModified{5,2} = '30';
           ConfigInfos.DataModified{5,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{5,4} = 'PlntVehRollMomentInertia';
           ConfigInfos.DataModified{5,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{5,6} = 'Body and Frame';

           ConfigInfos.DataModified{6,1} = 'PlntVehPitchMomentInertia';
           ConfigInfos.DataModified{6,2} = '55';
           ConfigInfos.DataModified{6,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{6,4} = 'PlntVehPitchMomentInertia';
           ConfigInfos.DataModified{6,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{6,6} = 'Body and Frame';

           ConfigInfos.DataModified{7,1} = 'PlntVehYawMomentInertia';
           ConfigInfos.DataModified{7,2} = '55';
           ConfigInfos.DataModified{7,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{7,4} = 'PlntVehYawMomentInertia';
           ConfigInfos.DataModified{7,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{7,6} = 'Body and Frame';

           ConfigInfos.DataModified{8,1} = 'PlntVehTrckWdth';
           ConfigInfos.DataModified{8,2} = '[1.2192 1.2192]';
           ConfigInfos.DataModified{8,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{8,4} = 'PlntVehTrckWdth';
           ConfigInfos.DataModified{8,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{8,6} = 'Body and Frame';

           ConfigInfos.DataModified{9,1} = 'PlntVehAeroFrntArea';
           ConfigInfos.DataModified{9,2} = '1.1';
           ConfigInfos.DataModified{9,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{9,4} = 'PlntVehAeroFrntArea';
           ConfigInfos.DataModified{9,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
           ConfigInfos.DataModified{9,6} = 'Body and Frame';

          ConfigInfos.DataModified{10,1} = 'PlntVehAeroDragCff';
          ConfigInfos.DataModified{10,2} = '1.5';
          ConfigInfos.DataModified{10,3} = 'PassVeh.sldd';
          ConfigInfos.DataModified{10,4} = 'PlntVehAeroDragCff';
          ConfigInfos.DataModified{10,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
          ConfigInfos.DataModified{10,6} = 'Body and Frame';

          ConfigInfos.DataModified{11,1} = 'PlntVehAeroLiftCff';
          ConfigInfos.DataModified{11,2} = '-3';
          ConfigInfos.DataModified{11,3} = 'PassVeh.sldd';
          ConfigInfos.DataModified{11,4} = 'PlntVehAeroLiftCff';
          ConfigInfos.DataModified{11,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
          ConfigInfos.DataModified{11,6} = 'Body and Frame';

          ConfigInfos.DataModified{12,1} = 'PlntVehAeroPitchCff';
          ConfigInfos.DataModified{12,2} = '-0.24';
          ConfigInfos.DataModified{12,3} = 'PassVeh.sldd';
          ConfigInfos.DataModified{12,4} = 'PlntVehAeroPitchCff';
          ConfigInfos.DataModified{12,5} = 'Vehicle Body 6DOF Longitudinal and Lateral';
          ConfigInfos.DataModified{12,6} = 'Body and Frame';

          ConfigInfos.DataModified{13,1} = 'PlntVehMultiBodySteerPinAngle';
          ConfigInfos.DataModified{13,2} = '[-90 0 90]';
          ConfigInfos.DataModified{13,3} = 'PassVehMultibody.sldd';
          ConfigInfos.DataModified{13,4} = 'PlntVehMultiBodySteerPinAngle';
          ConfigInfos.DataModified{13,5} = 'Multibody Steering System';
          ConfigInfos.DataModified{13,6} = 'Steering System';

          ConfigInfos.DataModified{14,1} = 'PlntVehMultiBodySteerRackTravel';
          ConfigInfos.DataModified{14,2} = '[-24.9 0 24.9]';
          ConfigInfos.DataModified{14,3} = 'PassVehMultibody.sldd';
          ConfigInfos.DataModified{14,4} = 'PlntVehMultiBodySteerRackTravel';
          ConfigInfos.DataModified{14,5} = 'Multibody Steering System';
          ConfigInfos.DataModified{14,6} = 'Steering System';

          ConfigInfos.DataModified{15,1} = 'PlntEngTqMax';
          ConfigInfos.DataModified{15,2} = '[27.1 34.6 38.6 37.7 36.9 38.6 40.7 41.4 42.7 47.2 46.8 46.1 46.4 45.8 43.1 40.0 37.3 33.9 30.5 27.1]';
          ConfigInfos.DataModified{15,3} = 'SimpleEngine.sldd';
          ConfigInfos.DataModified{15,4} = 'PlntEngTqMax';
          ConfigInfos.DataModified{15,5} = 'SI Simple Engine';
          ConfigInfos.DataModified{15,6} = 'Engine';

          ConfigInfos.DataModified{16,1} = 'PlntEngTqMaxBpt';
          ConfigInfos.DataModified{16,2} = '[0 3553 4105 4658 5211 5763 6316 6868 7421 7974 8526 9079 9632 10184 10737 11289 11842 12395 12947 13500]';
          ConfigInfos.DataModified{16,3} = 'SimpleEngine.sldd';
          ConfigInfos.DataModified{16,4} = 'PlntEngTqMaxBpt';
          ConfigInfos.DataModified{16,5} = 'SI Simple Engine';
          ConfigInfos.DataModified{16,6} = 'Engine';

          ConfigInfos.DataModified{17,1} = 'PlntTransGearNumVect';
          ConfigInfos.DataModified{17,2} = '[-1 0 1 2 3 4 5 6]';
          ConfigInfos.DataModified{17,3} = 'Drivetrain.sldd';
          ConfigInfos.DataModified{17,4} = 'PlntTransGearNumVect';
          ConfigInfos.DataModified{17,5} = 'Ideal Fixed Gear Transmission';
          ConfigInfos.DataModified{17,6} = 'Transmission';

          ConfigInfos.DataModified{18,1} = 'PlntTransGearRatioVect';
          ConfigInfos.DataModified{18,2} = '[-3 1 2.75 2 1.667 1.444 1.304 1.208]';
          ConfigInfos.DataModified{18,3} = 'Drivetrain.sldd';
          ConfigInfos.DataModified{18,4} = 'PlntTransGearRatioVect';
          ConfigInfos.DataModified{18,5} = 'Ideal Fixed Gear Transmission';
          ConfigInfos.DataModified{18,6} = 'Transmission';

          ConfigInfos.DataModified{19,1} = 'PlntTransEffVect';
          ConfigInfos.DataModified{19,2} = '[0.9 0.9 0.9 0.9 0.9 0.9 0.9, 0.9]';
          ConfigInfos.DataModified{19,3} = 'Drivetrain.sldd';
          ConfigInfos.DataModified{19,4} = 'PlntTransEffVect';
          ConfigInfos.DataModified{19,5} = 'Ideal Fixed Gear Transmission';
          ConfigInfos.DataModified{19,6} = 'Transmission';

          ConfigInfos.DataModified{20,1} = 'CtrlTcuTmUpSh';
          ConfigInfos.DataModified{20,2} = '0.1';
          ConfigInfos.DataModified{20,3} = 'Drivetrain.sldd';
          ConfigInfos.DataModified{20,4} = 'CtrlTcuTmUpSh';
          ConfigInfos.DataModified{20,5} = 'PRNDL Controller';
          ConfigInfos.DataModified{20,6} = 'Transmission Control Unit';

          ConfigInfos.DataModified{21,1} = 'CtrlTcuTmDnSh';
          ConfigInfos.DataModified{21,2} = '0.1';
          ConfigInfos.DataModified{21,3} = 'Drivetrain.sldd';
          ConfigInfos.DataModified{21,4} = 'CtrlTcuTmDnSh';
          ConfigInfos.DataModified{21,5} = 'PRNDL Controller';
          ConfigInfos.DataModified{21,6} = 'Transmission Control Unit';

          ConfigInfos.DataModified{22,1} = 'PlntDiffrntl2Ratio';
          ConfigInfos.DataModified{22,2} = '2.909';
          ConfigInfos.DataModified{22,3} = 'Drivetrain.sldd';
          ConfigInfos.DataModified{22,4} = 'PlntDiffrntl2Ratio';
          ConfigInfos.DataModified{22,5} = 'Limited Slip Differential Rear';
          ConfigInfos.DataModified{22,6} = 'Rear Differential System';

%% Test Plan
          ConfigInfos.TestPlan{1}.Source = 'Scenario.sldd';
            ConfigInfos.TestPlan{1}.Name = 'Increasing Steer';
           ConfigInfos.TestPlan{1}.Cycle = 'Disabled';
          ConfigInfos.TestPlan{1}.Driver = 'Predictive Driver';
       ConfigInfos.TestPlan{1}.Data{1,1} = 'ScnISHandwheelRate';
       ConfigInfos.TestPlan{1}.Data{1,2} = '13.5';
       ConfigInfos.TestPlan{1}.Data{2,1} = 'ScnISMaxHandwheelAng';
       ConfigInfos.TestPlan{1}.Data{2,2} = '30';
       ConfigInfos.TestPlan{1}.Data{3,1} = 'ScnISSteerHoldTime';
       ConfigInfos.TestPlan{1}.Data{3,2} = '2';
       ConfigInfos.TestPlan{1}.Data{4,1} = 'ScnISMaxLatAccel';
       ConfigInfos.TestPlan{1}.Data{4,2} = '0.6';
       ConfigInfos.TestPlan{1}.Data{5,1} = 'PlntVehInitLongPos';
       ConfigInfos.TestPlan{1}.Data{5,2} = '0';
       ConfigInfos.TestPlan{1}.Data{6,1} = 'PlntVehInitLatPos';
       ConfigInfos.TestPlan{1}.Data{6,2} = '0';
       ConfigInfos.TestPlan{1}.Data{7,1} = 'PlntVehInitVertPos';
       ConfigInfos.TestPlan{1}.Data{7,2} = '0';
       ConfigInfos.TestPlan{1}.Data{8,1} = 'PlntVehInitRollAng';
       ConfigInfos.TestPlan{1}.Data{8,2} = '0';
       ConfigInfos.TestPlan{1}.Data{9,1} = 'PlntVehInitPitchAng';
       ConfigInfos.TestPlan{1}.Data{9,2} = '0';
      ConfigInfos.TestPlan{1}.Data{10,1} = 'PlntVehInitYawAng';
      ConfigInfos.TestPlan{1}.Data{10,2} = '0';
      ConfigInfos.TestPlan{1}.Data{11,1} = 'ScnStartTime';
      ConfigInfos.TestPlan{1}.Data{11,2} = '2';
      ConfigInfos.TestPlan{1}.Data{12,1} = 'ScnLongVelRef';
      ConfigInfos.TestPlan{1}.Data{12,2} = '50';
      ConfigInfos.TestPlan{1}.Data{13,1} = 'ScnLongVelUnit';
      ConfigInfos.TestPlan{1}.Data{13,2} = 'mph';
      ConfigInfos.TestPlan{1}.Data{14,1} = 'ScnSteerDir';
      ConfigInfos.TestPlan{1}.Data{14,2} = 'Right';
      ConfigInfos.TestPlan{1}.Data{15,1} = 'ScnSimTime';
      ConfigInfos.TestPlan{1}.Data{15,2} = '60';
      ConfigInfos.TestPlan{1}.Data{16,1} = 'DriverPreviewDist';
      ConfigInfos.TestPlan{1}.Data{16,2} = '6';
      ConfigInfos.TestPlan{1}.Data{17,1} = 'DriverTimeConst';
      ConfigInfos.TestPlan{1}.Data{17,2} = '0.3';
      ConfigInfos.TestPlan{1}.Data{18,1} = 'DriverDrivelineRes';
      ConfigInfos.TestPlan{1}.Data{18,2} = '75';
      ConfigInfos.TestPlan{1}.Data{19,1} = 'DriverRollRes';
      ConfigInfos.TestPlan{1}.Data{19,2} = '800';
      ConfigInfos.TestPlan{1}.Data{20,1} = 'DriverShiftTime';
      ConfigInfos.TestPlan{1}.Data{20,2} = '0.1';
      ConfigInfos.TestPlan{1}.Data{21,1} = 'DriverTractiveForce';
      ConfigInfos.TestPlan{1}.Data{21,2} = '15000';
      ConfigInfos.TestPlan{1}.Data{22,1} = 'DriverFrontCornerStiff';
      ConfigInfos.TestPlan{1}.Data{22,2} = '40000';
      ConfigInfos.TestPlan{1}.Data{23,1} = 'DriverRearCornerStiff';
      ConfigInfos.TestPlan{1}.Data{23,2} = '40000';
      ConfigInfos.TestPlan{1}.Data{24,1} = 'DriverWheelRange';
      ConfigInfos.TestPlan{1}.Data{24,2} = '1.0472';

%% Selected Logging Signals
ConfigInfos.SelectedSignals = {
'Body.BdyFrm.Cg.Vel.xdot',...
'Body.BdyFrm.Cg.Acc.ax',...
'Body.BdyFrm.Cg.Acc.ay',...
'Body.BdyFrm.Cg.Acc.az',...
'Driver.SteerFdbk',...
'Driver.AccelFdbk',...
'Driver.DecelFdbk',...
'Driver.GearFdbk',...
'Trans.Info.Trans.TransGear',...
'Trans.Info.Trans.TransGearCmd',...
'Engine.EngTrq',...
'Engine.EngSpdOut',...
};

%% Finish
